### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ebidel** [Polymer/core-image#17]
_From @sauravskumar99 on February 19, 2015 13:31_

Documentation Core Elements > Core image > Attributes (Red Box) > Preload (section) the description has a typing error in the last word. Should be "then" but is mistyped as "the"

_Copied from original issue: Polymer/polymer#1205_

**Comment by ebidel** [comment]
@kevinpschaaf how is that sentence supposed to read?

**Comment by sauravskumar99** [comment]
i think the last word should be "THEN" but it is mistyped as "THE"... in ### Documentation > Core Elements > Core image > Attributes (Red Box) > Preload (section)
