### ISSUE TITLE
<core-image> doesnt work with page templating

### ISSUE THREAD

**Issue by nousacademy** [Polymer/core-image#21]
Im not able to display an image using 
    < core-image > when using < core-pages > . The images don't display, but when I use the regular < img > tag they show up.

**Comment by zdarovka** [comment]
Are you sure, that you have your core-image sized?

**Comment by nousacademy** [comment]
yeah it was at 100% width

**Comment by zdarovka** [comment]
Try to style precisely on pixel please. I think core-image can not have relative dimensions

**Comment by nousacademy** [comment]
yeah now it works, oh that sucks! Thanks!
