### ISSUE TITLE
Did core-image support lazyload image when visible ?

### ISSUE THREAD

**Issue by minhlong139** [Polymer/core-image#27]
Hi all,

Did core-image support lazyload image when visible 
Some thing like http://www.appelsiini.net/projects/lazyload 

Thanks

**Comment by ebidel** [comment]
core-images is deprecated in favor of https://elements.polymer-project.org/elements/iron-image.

You could easily hook up the lazy loading to iron-scroll-threshold (https://elements.polymer-project.org/elements/iron-scroll-threshold) to detect when the user has scrolled to that part of the page. iron-image has `fade` and `preload` attribute that would be useful.
