### ISSUE TITLE
<img src="album/01.png" style="width:100%"/>

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/core-image#4]
Can not reproduce this http://sea-is-snow.appspot.com/ when replacing img with `<core-image sizing="cover"` it results in pictures height 0. Any advice please to achive a relative size when you make the screen bigger?

**Comment by ssorallen** [comment]
Is this still an issue? I'm not sure I follow what you aren't currently able to do.

**Comment by gertcuykens** [comment]
no this can be closed, after playing around with `min-height` and `min-width` I can make a flexible image like a normal image

**Comment by Zippersk** [comment]
@gertcuykens how do you figure it? I am having same issue.

**Comment by gertcuykens** [comment]
@Zippersk Just adding min-height 100% and min-width 100%  if i remember correctly.
